name: somnio_flutter_challenge
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  dio: ^5.2.1+1
  hooks_riverpod: ^2.5.2
  flutter_hooks: 0.20.5
  json_annotation: ^4.7.0
  shared_preferences: ^2.3.2
  riverpod_annotation: ^2.3.5
  riverpod_test: ^0.1.6
  mocktail_image_network: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: 2.4.12
  custom_lint: 0.6.7
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  json_serializable: ^6.5.3
  mocktail: ^0.3.0


flutter:
  uses-material-design: true
